version: '3.8'

services:
  app:
    image: sustainable-tourism-app
    build:
      context: .
    ports:
      - "8000"  # Optional for debugging; the load balancer will handle external traffic
    deploy:
      replicas: 1  # Set this to 1 initially; scale dynamically
    environment:
      - PORT=8000

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Nginx will handle all incoming traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
